/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/FinishedShopping`; params?: Router.UnknownInputParams; } | { pathname: `/GeneratedList`; params?: Router.UnknownInputParams; } | { pathname: `/NewUserScreen`; params?: Router.UnknownInputParams; } | { pathname: `/NextPurchaseDate`; params?: Router.UnknownInputParams; } | { pathname: `/create-account`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/select-items`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/FinishedShopping`; params?: Router.UnknownOutputParams; } | { pathname: `/GeneratedList`; params?: Router.UnknownOutputParams; } | { pathname: `/NewUserScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/NextPurchaseDate`; params?: Router.UnknownOutputParams; } | { pathname: `/create-account`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/select-items`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/FinishedShopping${`?${string}` | `#${string}` | ''}` | `/GeneratedList${`?${string}` | `#${string}` | ''}` | `/NewUserScreen${`?${string}` | `#${string}` | ''}` | `/NextPurchaseDate${`?${string}` | `#${string}` | ''}` | `/create-account${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/select-items${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/FinishedShopping`; params?: Router.UnknownInputParams; } | { pathname: `/GeneratedList`; params?: Router.UnknownInputParams; } | { pathname: `/NewUserScreen`; params?: Router.UnknownInputParams; } | { pathname: `/NextPurchaseDate`; params?: Router.UnknownInputParams; } | { pathname: `/create-account`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/select-items`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
